### ISSUE TITLE
Delete button in the wallet is not deleting wallet.

### ISSUE THREAD

**Issue by sabbir-ahmed12** [uiowahjmjohnsonselt2024/projectdirectory-selt_2024_team_009#132]
### Description

The delete buttons in the different pages of the game is not working. It redirects to a different page instead of deleting the expected item.

### To Reproduce

1. Go to 'Profile'
2. Go to 'My Wallet'
3. Click on 'Delete Wallet'

### Expected behavior

The wallet should be deleted and confirmed using a flash message.

**Comment by mzen17** [comment]
Do you think this should be patched or if we should remove the ability to delete the wallet? Do you think it is neccessary to maintain a feature to delete wallet?

**Comment by sabbir-ahmed12** [comment]
> Do you think this should be patched or if we should remove the ability to delete the wallet? Do you think it is neccessary to maintain a feature to delete wallet?

I don't know! There was a button to delete the wallet but it was not working. However, I've pushed the changes with the existing PR.

**Comment by mzen17** [comment]
Got it. If you've already fixed it, wd can keep the feature!

Mike
