### ISSUE TITLE
Select and enter server to play on

### ISSUE THREAD

**Issue by jackosse17** [uiowahjmjohnsonselt2024/projectdirectory-selt_2024_team_009#8]
As a player, I want to be able to select different servers to play from, so I can play with my friends

Acceptance Criteria:

A user, on the server page, will be able to select a server and click a 'join' button
the user will then be added to the server and be brought to the game page where they can play
A user will also be able choose between different servers which are added to the game, both automatically and by other players

**Comment by avinashreddymudireddy** [comment]
The feature has some bug in the production deployment. Works fin in development.
